apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-app
        image: gcr.io/dockerhelloworld-485819/hello-world-app:v22 # Update to v16 after code change
        ports:
        - containerPort: 8080
        env:
        - name: GCP_BUCKET_NAME
          value: "housing-data-for-testing"
        volumeMounts:
        # Mount for GCP Credentials
        - name: google-cloud-key
          mountPath: /var/secrets/google
          readOnly: true
        # NEW: Mount for Persistent MLflow Database
        - name: mlflow-db-storage
          mountPath: /app/data
      volumes:
      # Volume for GCP Credentials
      - name: google-cloud-key
        secret:
          secretName: gcp-key
      # NEW: Volume for Persistent MLflow Database
      - name: mlflow-db-storage
        persistentVolumeClaim:
          claimName: mlflow-sqlite-pvc